#This can probably be extracted from:
#https://pypi.python.org/pypi/mendeleev/0.2.8#downloads

ptable = {1: {'Group': 1, 'Name': u'Hydrogen', 'Period': 1, 'Symbol': u'H'},
 2: {'Group': 18, 'Name': u'Helium', 'Period': 1, 'Symbol': u'He'},
 3: {'Group': 1, 'Name': u'Lithium', 'Period': 2, 'Symbol': u'Li'},
 4: {'Group': 2, 'Name': u'Beryllium', 'Period': 2, 'Symbol': u'Be'},
 5: {'Group': 13, 'Name': u'Boron', 'Period': 2, 'Symbol': u'B'},
 6: {'Group': 14, 'Name': u'Carbon', 'Period': 2, 'Symbol': u'C'},
 7: {'Group': 15, 'Name': u'Nitrogen', 'Period': 2, 'Symbol': u'N'},
 8: {'Group': 16, 'Name': u'Oxygen', 'Period': 2, 'Symbol': u'O'},
 9: {'Group': 17, 'Name': u'Fluorine', 'Period': 2, 'Symbol': u'F'},
 10: {'Group': 18, 'Name': u'Neon', 'Period': 2, 'Symbol': u'Ne'},
 11: {'Group': 1, 'Name': u'Sodium', 'Period': 3, 'Symbol': u'Na'},
 12: {'Group': 2, 'Name': u'Magnesium', 'Period': 3, 'Symbol': u'Mg'},
 13: {'Group': 13, 'Name': u'Aluminum', 'Period': 3, 'Symbol': u'Al'},
 14: {'Group': 14, 'Name': u'Silicon', 'Period': 3, 'Symbol': u'Si'},
 15: {'Group': 15, 'Name': u'Phosphorus', 'Period': 3, 'Symbol': u'P'},
 16: {'Group': 16, 'Name': u'Sulfur', 'Period': 3, 'Symbol': u'S'},
 17: {'Group': 17, 'Name': u'Chlorine', 'Period': 3, 'Symbol': u'Cl'},
 18: {'Group': 18, 'Name': u'Argon', 'Period': 3, 'Symbol': u'Ar'},
 19: {'Group': 1, 'Name': u'Potassium', 'Period': 4, 'Symbol': u'K'},
 20: {'Group': 2, 'Name': u'Calcium', 'Period': 4, 'Symbol': u'Ca'},
 21: {'Group': 3, 'Name': u'Scandium', 'Period': 4, 'Symbol': u'Sc'},
 22: {'Group': 4, 'Name': u'Titanium', 'Period': 4, 'Symbol': u'Ti'},
 23: {'Group': 5, 'Name': u'Vanadium', 'Period': 4, 'Symbol': u'V'},
 24: {'Group': 6, 'Name': u'Chromium', 'Period': 4, 'Symbol': u'Cr'},
 25: {'Group': 7, 'Name': u'Manganese', 'Period': 4, 'Symbol': u'Mn'},
 26: {'Group': 8, 'Name': u'Iron', 'Period': 4, 'Symbol': u'Fe'},
 27: {'Group': 9, 'Name': u'Cobalt', 'Period': 4, 'Symbol': u'Co'},
 28: {'Group': 10, 'Name': u'Nickel', 'Period': 4, 'Symbol': u'Ni'},
 29: {'Group': 11, 'Name': u'Copper', 'Period': 4, 'Symbol': u'Cu'},
 30: {'Group': 12, 'Name': u'Zinc', 'Period': 4, 'Symbol': u'Zn'},
 31: {'Group': 13, 'Name': u'Gallium', 'Period': 4, 'Symbol': u'Ga'},
 32: {'Group': 14, 'Name': u'Germanium', 'Period': 4, 'Symbol': u'Ge'},
 33: {'Group': 15, 'Name': u'Arsenic', 'Period': 4, 'Symbol': u'As'},
 34: {'Group': 16, 'Name': u'Selenium', 'Period': 4, 'Symbol': u'Se'},
 35: {'Group': 17, 'Name': u'Bromine', 'Period': 4, 'Symbol': u'Br'},
 36: {'Group': 18, 'Name': u'Krypton', 'Period': 4, 'Symbol': u'Kr'},
 37: {'Group': 1, 'Name': u'Rubidium', 'Period': 5, 'Symbol': u'Rb'},
 38: {'Group': 2, 'Name': u'Strontium', 'Period': 5, 'Symbol': u'Sr'},
 39: {'Group': 3, 'Name': u'Yttrium', 'Period': 5, 'Symbol': u'Y'},
 40: {'Group': 4, 'Name': u'Zirconium', 'Period': 5, 'Symbol': u'Zr'},
 41: {'Group': 5, 'Name': u'Niobium', 'Period': 5, 'Symbol': u'Nb'},
 42: {'Group': 6, 'Name': u'Molybdenum', 'Period': 5, 'Symbol': u'Mo'},
 43: {'Group': 7, 'Name': u'Technetium', 'Period': 5, 'Symbol': u'Tc'},
 44: {'Group': 8, 'Name': u'Ruthenium', 'Period': 5, 'Symbol': u'Ru'},
 45: {'Group': 9, 'Name': u'Rhodium', 'Period': 5, 'Symbol': u'Rh'},
 46: {'Group': 10, 'Name': u'Palladium', 'Period': 5, 'Symbol': u'Pd'},
 47: {'Group': 11, 'Name': u'Silver', 'Period': 5, 'Symbol': u'Ag'},
 48: {'Group': 12, 'Name': u'Cadmium', 'Period': 5, 'Symbol': u'Cd'},
 49: {'Group': 13, 'Name': u'Indium', 'Period': 5, 'Symbol': u'In'},
 50: {'Group': 14, 'Name': u'Tin', 'Period': 5, 'Symbol': u'Sn'},
 51: {'Group': 15, 'Name': u'Antimony', 'Period': 5, 'Symbol': u'Sb'},
 52: {'Group': 16, 'Name': u'Tellurium', 'Period': 5, 'Symbol': u'Te'},
 53: {'Group': 17, 'Name': u'Iodine', 'Period': 5, 'Symbol': u'I'},
 54: {'Group': 18, 'Name': u'Xenon', 'Period': 5, 'Symbol': u'Xe'},
 55: {'Group': 1, 'Name': u'Cesium', 'Period': 6, 'Symbol': u'Cs'},
 56: {'Group': 2, 'Name': u'Barium', 'Period': 6, 'Symbol': u'Ba'},
 57: {'Group': None, 'Name': u'Lanthanum', 'Period': 6, 'Symbol': u'La'},
 58: {'Group': None, 'Name': u'Cerium', 'Period': 6, 'Symbol': u'Ce'},
 59: {'Group': None, 'Name': u'Praseodymium', 'Period': 6, 'Symbol': u'Pr'},
 60: {'Group': None, 'Name': u'Neodymium', 'Period': 6, 'Symbol': u'Nd'},
 61: {'Group': None, 'Name': u'Promethium', 'Period': 6, 'Symbol': u'Pm'},
 62: {'Group': None, 'Name': u'Samarium', 'Period': 6, 'Symbol': u'Sm'},
 63: {'Group': None, 'Name': u'Europium', 'Period': 6, 'Symbol': u'Eu'},
 64: {'Group': None, 'Name': u'Gadolinium', 'Period': 6, 'Symbol': u'Gd'},
 65: {'Group': None, 'Name': u'Terbium', 'Period': 6, 'Symbol': u'Tb'},
 66: {'Group': None, 'Name': u'Dysprosium', 'Period': 6, 'Symbol': u'Dy'},
 67: {'Group': None, 'Name': u'Holmium', 'Period': 6, 'Symbol': u'Ho'},
 68: {'Group': None, 'Name': u'Erbium', 'Period': 6, 'Symbol': u'Er'},
 69: {'Group': None, 'Name': u'Thulium', 'Period': 6, 'Symbol': u'Tm'},
 70: {'Group': None, 'Name': u'Ytterbium', 'Period': 6, 'Symbol': u'Yb'},
 71: {'Group': 3, 'Name': u'Lutetium', 'Period': 6, 'Symbol': u'Lu'},
 72: {'Group': 4, 'Name': u'Hafnium', 'Period': 6, 'Symbol': u'Hf'},
 73: {'Group': 5, 'Name': u'Tantalum', 'Period': 6, 'Symbol': u'Ta'},
 74: {'Group': 6, 'Name': u'Tungsten', 'Period': 6, 'Symbol': u'W'},
 75: {'Group': 7, 'Name': u'Rhenium', 'Period': 6, 'Symbol': u'Re'},
 76: {'Group': 8, 'Name': u'Osmium', 'Period': 6, 'Symbol': u'Os'},
 77: {'Group': 9, 'Name': u'Iridium', 'Period': 6, 'Symbol': u'Ir'},
 78: {'Group': 10, 'Name': u'Platinum', 'Period': 6, 'Symbol': u'Pt'},
 79: {'Group': 11, 'Name': u'Gold', 'Period': 6, 'Symbol': u'Au'},
 80: {'Group': 12, 'Name': u'Mercury', 'Period': 6, 'Symbol': u'Hg'},
 81: {'Group': 13, 'Name': u'Thallium', 'Period': 6, 'Symbol': u'Tl'},
 82: {'Group': 14, 'Name': u'Lead', 'Period': 6, 'Symbol': u'Pb'},
 83: {'Group': 15, 'Name': u'Bismuth', 'Period': 6, 'Symbol': u'Bi'},
 84: {'Group': 16, 'Name': u'Polonium', 'Period': 6, 'Symbol': u'Po'},
 85: {'Group': 17, 'Name': u'Astatine', 'Period': 6, 'Symbol': u'At'},
 86: {'Group': 18, 'Name': u'Radon', 'Period': 6, 'Symbol': u'Rn'},
 87: {'Group': 1, 'Name': u'Francium', 'Period': 7, 'Symbol': u'Fr'},
 88: {'Group': 2, 'Name': u'Radium', 'Period': 7, 'Symbol': u'Ra'},
 89: {'Group': None, 'Name': u'Actinium', 'Period': 7, 'Symbol': u'Ac'},
 90: {'Group': None, 'Name': u'Thorium', 'Period': 7, 'Symbol': u'Th'},
 91: {'Group': None, 'Name': u'Protactinium', 'Period': 7, 'Symbol': u'Pa'},
 92: {'Group': None, 'Name': u'Uranium', 'Period': 7, 'Symbol': u'U'},
 93: {'Group': None, 'Name': u'Neptunium', 'Period': 7, 'Symbol': u'Np'},
 94: {'Group': None, 'Name': u'Plutonium', 'Period': 7, 'Symbol': u'Pu'},
 95: {'Group': None, 'Name': u'Americium', 'Period': 7, 'Symbol': u'Am'},
 96: {'Group': None, 'Name': u'Curium', 'Period': 7, 'Symbol': u'Cm'},
 97: {'Group': None, 'Name': u'Berkelium', 'Period': 7, 'Symbol': u'Bk'},
 98: {'Group': None, 'Name': u'Californium', 'Period': 7, 'Symbol': u'Cf'},
 99: {'Group': None, 'Name': u'Einsteinium', 'Period': 7, 'Symbol': u'Es'},
 100: {'Group': None, 'Name': u'Fermium', 'Period': 7, 'Symbol': u'Fm'},
 101: {'Group': None, 'Name': u'Mendelevium', 'Period': 7, 'Symbol': u'Md'},
 102: {'Group': None, 'Name': u'Nobelium', 'Period': 7, 'Symbol': u'No'},
 103: {'Group': 3, 'Name': u'Lawrencium', 'Period': 7, 'Symbol': u'Lr'},
 104: {'Group': 4, 'Name': u'Rutherfordium', 'Period': 7, 'Symbol': u'Rf'},
 105: {'Group': 5, 'Name': u'Dubnium', 'Period': 7, 'Symbol': u'Db'},
 106: {'Group': 6, 'Name': u'Seaborgium', 'Period': 7, 'Symbol': u'Sg'},
 107: {'Group': 7, 'Name': u'Bohrium', 'Period': 7, 'Symbol': u'Bh'},
 108: {'Group': 8, 'Name': u'Hassium', 'Period': 7, 'Symbol': u'Hs'},
 109: {'Group': 9, 'Name': u'Meitnerium', 'Period': 7, 'Symbol': u'Mt'},
 110: {'Group': 10, 'Name': u'Darmstadtium', 'Period': 7, 'Symbol': u'Ds'},
 111: {'Group': 11, 'Name': u'Roentgenium', 'Period': 7, 'Symbol': u'Rg'},
 112: {'Group': 12, 'Name': u'Copernicium', 'Period': 7, 'Symbol': u'Cn'},
 113: {'Group': 13, 'Name': u'Nihonium', 'Period': 7, 'Symbol': u'Nh'},
 114: {'Group': 14, 'Name': u'Flerovium', 'Period': 7, 'Symbol': u'Fl'},
 115: {'Group': 15, 'Name': u'Moscovium', 'Period': 7, 'Symbol': u'Mc'},
 116: {'Group': 16, 'Name': u'Livermorium', 'Period': 7, 'Symbol': u'Lv'},
 117: {'Group': 17, 'Name': u'Tennessine', 'Period': 7, 'Symbol': u'Ts'},
 118: {'Group': 18, 'Name': u'Oganesson', 'Period': 7, 'Symbol': u'Og'}}
 
symboltoint ={u'Ac': 89,
 u'Ag': 47,
 u'Al': 13,
 u'Am': 95,
 u'Ar': 18,
 u'As': 33,
 u'At': 85,
 u'Au': 79,
 u'B': 5,
 u'Ba': 56,
 u'Be': 4,
 u'Bh': 107,
 u'Bi': 83,
 u'Bk': 97,
 u'Br': 35,
 u'C': 6,
 u'Ca': 20,
 u'Cd': 48,
 u'Ce': 58,
 u'Cf': 98,
 u'Cl': 17,
 u'Cm': 96,
 u'Cn': 112,
 u'Co': 27,
 u'Cr': 24,
 u'Cs': 55,
 u'Cu': 29,
 u'Db': 105,
 u'Ds': 110,
 u'Dy': 66,
 u'Er': 68,
 u'Es': 99,
 u'Eu': 63,
 u'F': 9,
 u'Fe': 26,
 u'Fl': 114,
 u'Fm': 100,
 u'Fr': 87,
 u'Ga': 31,
 u'Gd': 64,
 u'Ge': 32,
 u'H': 1,
 u'He': 2,
 u'Hf': 72,
 u'Hg': 80,
 u'Ho': 67,
 u'Hs': 108,
 u'I': 53,
 u'In': 49,
 u'Ir': 77,
 u'K': 19,
 u'Kr': 36,
 u'La': 57,
 u'Li': 3,
 u'Lr': 103,
 u'Lu': 71,
 u'Lv': 116,
 u'Mc': 115,
 u'Md': 101,
 u'Mg': 12,
 u'Mn': 25,
 u'Mo': 42,
 u'Mt': 109,
 u'N': 7,
 u'Na': 11,
 u'Nb': 41,
 u'Nd': 60,
 u'Ne': 10,
 u'Nh': 113,
 u'Ni': 28,
 u'No': 102,
 u'Np': 93,
 u'O': 8,
 u'Og': 118,
 u'Os': 76,
 u'P': 15,
 u'Pa': 91,
 u'Pb': 82,
 u'Pd': 46,
 u'Pm': 61,
 u'Po': 84,
 u'Pr': 59,
 u'Pt': 78,
 u'Pu': 94,
 u'Ra': 88,
 u'Rb': 37,
 u'Re': 75,
 u'Rf': 104,
 u'Rg': 111,
 u'Rh': 45,
 u'Rn': 86,
 u'Ru': 44,
 u'S': 16,
 u'Sb': 51,
 u'Sc': 21,
 u'Se': 34,
 u'Sg': 106,
 u'Si': 14,
 u'Sm': 62,
 u'Sn': 50,
 u'Sr': 38,
 u'Ta': 73,
 u'Tb': 65,
 u'Tc': 43,
 u'Te': 52,
 u'Th': 90,
 u'Ti': 22,
 u'Tl': 81,
 u'Tm': 69,
 u'Ts': 117,
 u'U': 92,
 u'V': 23,
 u'W': 74,
 u'Xe': 54,
 u'Y': 39,
 u'Yb': 70,
 u'Zn': 30,
 u'Zr': 40}
